export interface IClock {
	date: String
	date_time: String
	date_time_txt: String
	date_time_wti: String
	date_time_ymd: String
	day: String
	day_abbr: String
	day_full: String
	day_wilz: String
	dst: String
	dst_observes: String
	hour_12_wilz: String
	hour_12_wolz: String
	hour_24_wilz: String
	hour_24_wolz: String
	hour_am_pm: String
	minutes: String
	month: String
	month_abbr: String
	month_days: String
	month_full: String
	month_wilz: String
	offset_gmt: String
	offset_hours: String
	offset_minutes: String
	offset_seconds: String
	offset_tzab: String
	offset_tzfull: String
	offset_tzid: String
	seconds: String
	time: String
	timeday_gen: String
	timeday_spe: String
	tz_string: String
	week: String
	year: String
	year_abbr: String
}
